#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-seaborn
Version  : 0.12.0
Release  : 48
URL      : https://files.pythonhosted.org/packages/0a/87/9d713b302b7319f58e76f37fb2308377035c594b76bd50fe3696dad3a27e/seaborn-0.12.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/0a/87/9d713b302b7319f58e76f37fb2308377035c594b76bd50fe3696dad3a27e/seaborn-0.12.0.tar.gz
Summary  : Statistical data visualization
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: pypi-seaborn-license = %{version}-%{release}
Requires: pypi-seaborn-python = %{version}-%{release}
Requires: pypi-seaborn-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)

%description
<img src="https://raw.githubusercontent.com/mwaskom/seaborn/master/doc/_static/logo-wide-lightbg.svg"><br>

%package license
Summary: license components for the pypi-seaborn package.
Group: Default

%description license
license components for the pypi-seaborn package.


%package python
Summary: python components for the pypi-seaborn package.
Group: Default
Requires: pypi-seaborn-python3 = %{version}-%{release}

%description python
python components for the pypi-seaborn package.


%package python3
Summary: python3 components for the pypi-seaborn package.
Group: Default
Requires: python3-core
Provides: pypi(seaborn)
Requires: pypi(matplotlib)
Requires: pypi(numpy)
Requires: pypi(pandas)

%description python3
python3 components for the pypi-seaborn package.


%prep
%setup -q -n seaborn-0.12.0
cd %{_builddir}/seaborn-0.12.0
pushd ..
cp -a seaborn-0.12.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1662481055
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-seaborn
cp %{_builddir}/seaborn-%{version}/licences/HUSL_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/3284262e860227419fea272a5ab2a954dae740c0 || :
cp %{_builddir}/seaborn-%{version}/licences/PACKAGING_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/fdc0e4eabc45522b079deff7d03d70528d775dc0 || :
cp %{_builddir}/seaborn-%{version}/licences/SCIPY_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/224344942fe3a15ac074df8f635f3e7b445f5b2e || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-seaborn/224344942fe3a15ac074df8f635f3e7b445f5b2e
/usr/share/package-licenses/pypi-seaborn/3284262e860227419fea272a5ab2a954dae740c0
/usr/share/package-licenses/pypi-seaborn/fdc0e4eabc45522b079deff7d03d70528d775dc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
