#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v3
# autospec commit: c1050fe
#
Name     : pypi-seaborn
Version  : 0.13.1
Release  : 58
URL      : https://files.pythonhosted.org/packages/33/9c/86a12a4d83602cff440f16ffd1b77a9aef614563de9ebb114b755387d654/seaborn-0.13.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/33/9c/86a12a4d83602cff440f16ffd1b77a9aef614563de9ebb114b755387d654/seaborn-0.13.1.tar.gz
Summary  : Statistical data visualization
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: pypi-seaborn-license = %{version}-%{release}
Requires: pypi-seaborn-python = %{version}-%{release}
Requires: pypi-seaborn-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<img src="https://raw.githubusercontent.com/mwaskom/seaborn/master/doc/_static/logo-wide-lightbg.svg"><br>

%package license
Summary: license components for the pypi-seaborn package.
Group: Default

%description license
license components for the pypi-seaborn package.


%package python
Summary: python components for the pypi-seaborn package.
Group: Default
Requires: pypi-seaborn-python3 = %{version}-%{release}

%description python
python components for the pypi-seaborn package.


%package python3
Summary: python3 components for the pypi-seaborn package.
Group: Default
Requires: python3-core
Provides: pypi(seaborn)
Requires: pypi(matplotlib)
Requires: pypi(numpy)
Requires: pypi(pandas)

%description python3
python3 components for the pypi-seaborn package.


%prep
%setup -q -n seaborn-0.13.1
cd %{_builddir}/seaborn-0.13.1
pushd ..
cp -a seaborn-0.13.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1704142062
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . matplotlib
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
pypi-dep-fix.py . matplotlib
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-seaborn
cp %{_builddir}/seaborn-%{version}/licences/APPDIRS_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/a371eec7d43f0397248ae6203e5dfc866f2f7ed8 || :
cp %{_builddir}/seaborn-%{version}/licences/HUSL_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/3284262e860227419fea272a5ab2a954dae740c0 || :
cp %{_builddir}/seaborn-%{version}/licences/NUMPYDOC_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/df4f727b25238b8a4be050714fe3f1cb06b17f75 || :
cp %{_builddir}/seaborn-%{version}/licences/PACKAGING_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/fdc0e4eabc45522b079deff7d03d70528d775dc0 || :
cp %{_builddir}/seaborn-%{version}/licences/SCIPY_LICENSE %{buildroot}/usr/share/package-licenses/pypi-seaborn/224344942fe3a15ac074df8f635f3e7b445f5b2e || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
pypi-dep-fix.py %{buildroot} matplotlib
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-seaborn/224344942fe3a15ac074df8f635f3e7b445f5b2e
/usr/share/package-licenses/pypi-seaborn/3284262e860227419fea272a5ab2a954dae740c0
/usr/share/package-licenses/pypi-seaborn/a371eec7d43f0397248ae6203e5dfc866f2f7ed8
/usr/share/package-licenses/pypi-seaborn/df4f727b25238b8a4be050714fe3f1cb06b17f75
/usr/share/package-licenses/pypi-seaborn/fdc0e4eabc45522b079deff7d03d70528d775dc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
